/**
 * lib/reports.ts — Generate markdown output files from the DB
 *
 * All generated files carry a <!-- GENERATED --> header.
 * The DB is always the source of truth; these are committed snapshots.
 */

import type { DatabaseSync } from 'node:sqlite';
import { tasksByProject, dependenciesByProject, recentAudit, roiSummary, totalHours } from './db.ts';
import type { Task, Project } from './db.ts';
import { computeCpm } from './cpm.ts';
import type { CpmNode, CpmEdge } from './cpm.ts';

// ── tasks.md ──────────────────────────────────────────────────────────────────

export function reportTasks(db: DatabaseSync, project: Project): string {
  const tasks = tasksByProject(db, project.id);
  const deps  = dependenciesByProject(db, project.id);

  // Group by phase
  const phases = new Map<string, Task[]>();
  for (const t of tasks) {
    const key = t.phase ?? 'Unphased';
    if (!phases.has(key)) phases.set(key, []);
    phases.get(key)!.push(t);
  }

  // Build slug→id map for dep display
  const idToSlug = new Map(tasks.map(t => [t.id, t.slug]));
  const predecessorMap = new Map<number, number[]>(); // task.id → predecessor task.ids
  for (const d of deps) {
    if (!predecessorMap.has(d.successor_id)) predecessorMap.set(d.successor_id, []);
    predecessorMap.get(d.successor_id)!.push(d.predecessor_id);
  }

  const date = new Date().toISOString().slice(0, 10);
  const lines: string[] = [
    `# ${project.name} — Tasks`,
    `<!-- GENERATED by crux on ${date} — edit the DB, not this file -->`,
    '',
  ];

  // Summary counts
  const byStatus = (s: string) => tasks.filter(t => t.status === s).length;
  lines.push(
    `**Total:** ${tasks.length} | **Done:** ${byStatus('done')} | **Open:** ${byStatus('open')} | **In Progress:** ${byStatus('in-progress')} | **Blocked:** ${byStatus('blocked')}`,
    '',
  );

  for (const [phase, phaseTasks] of phases) {
    lines.push(`## ${phase}`, '');
    lines.push('| Slug | Title | Status | Depends On |');
    lines.push('|---|---|---|---|');
    for (const t of phaseTasks) {
      const preds = (predecessorMap.get(t.id) ?? []).map(id => idToSlug.get(id) ?? '?').join(', ') || '—';
      const status = statusBadge(t.status);
      lines.push(`| \`${t.slug}\` | ${t.title} | ${status} | ${preds} |`);
    }
    lines.push('');
  }

  // Critical path (if CPM data exists)
  const criticalTasks = tasks.filter(t => t.is_critical && t.status !== 'done');
  if (criticalTasks.length > 0) {
    lines.push('## Critical Path', '');
    lines.push(criticalTasks.map(t => `\`${t.slug}\``).join(' → '));
    lines.push('');
  }

  return lines.join('\n');
}

// ── status report ─────────────────────────────────────────────────────────────

export function reportStatus(db: DatabaseSync, project: Project): string {
  const tasks  = tasksByProject(db, project.id);
  const deps   = dependenciesByProject(db, project.id);
  const audit  = recentAudit(db, project.id, 10);
  const roi    = roiSummary(db, project.id);
  const hours  = totalHours(db, project.id);
  const date   = new Date().toISOString().slice(0, 10);

  // CPM
  const nodes: CpmNode[] = tasks.map(t => ({
    id: t.id, slug: t.slug, title: t.title, duration: t.duration_days ?? 1, phase: t.phase,
  }));
  const edges: CpmEdge[] = deps.map(d => ({ predecessor_id: d.predecessor_id, successor_id: d.successor_id }));
  let cpmSummary = '';
  try {
    const cpm = computeCpm(nodes, edges);
    cpmSummary = `**Critical Path:** ${cpm.critical_path.join(' → ') || 'none'}  \n**Project Duration:** ${cpm.project_duration} days`;
  } catch (err: unknown) {
    cpmSummary = `**CPM Error:** ${(err as Error).message}`;
  }

  const lines: string[] = [
    `# ${project.name} — Status Report`,
    `<!-- GENERATED by crux on ${date} — edit the DB, not this file -->`,
    `**Date:** ${date}`,
    '',
    '## Progress',
    `| Status | Count |`,
    `|---|---|`,
    `| Done | ${tasks.filter(t => t.status === 'done').length} |`,
    `| In Progress | ${tasks.filter(t => t.status === 'in-progress').length} |`,
    `| Open | ${tasks.filter(t => t.status === 'open').length} |`,
    `| Blocked | ${tasks.filter(t => t.status === 'blocked').length} |`,
    `| Total | ${tasks.length} |`,
    '',
    '## Schedule',
    cpmSummary,
    '',
    '## ROI',
    `| Metric | Value |`,
    `|---|---|`,
    `| Hours invested | ${hours.toFixed(1)}h |`,
    `| Revenue | ${roi.revenue.toFixed(2)} AUD |`,
    `| Cost | ${roi.cost.toFixed(2)} AUD |`,
    `| Expected (prob-adj) | ${roi.expected.toFixed(2)} AUD |`,
    '',
    '## Recent Activity',
    '',
  ];

  if (audit.length === 0) {
    lines.push('_No recent activity._');
  } else {
    for (const a of audit) {
      lines.push(`- \`${a.created_at}\` [${a.actor}] **${a.event}**${a.detail ? ': ' + a.detail : ''}`);
    }
  }
  lines.push('');

  return lines.join('\n');
}

// ── ADR report ────────────────────────────────────────────────────────────────

export function reportAdr(db: DatabaseSync, projectId: string, adrId: number): string {
  const adr = db.prepare('SELECT * FROM adrs WHERE id = ? AND project_id = ?').get(adrId, projectId) as {
    number: number; title: string; status: string;
    context: string | null; decision: string | null; consequences: string | null; created_at: string;
  } | null;

  if (!adr) throw new Error(`ADR ${adrId} not found`);

  const tasks = db.prepare(`
    SELECT t.slug, t.title, t.status FROM task_adrs ta
    JOIN tasks t ON t.id = ta.task_id
    WHERE ta.adr_id = ?
  `).all(adrId) as Array<{ slug: string; title: string; status: string }>;

  const num  = String(adr.number).padStart(4, '0');
  const date = adr.created_at.slice(0, 10);

  const lines: string[] = [
    `# ADR-${num}: ${adr.title}`,
    `<!-- GENERATED by crux — edit the DB, not this file -->`,
    '',
    `**Status:** ${adr.status}  `,
    `**Date:** ${date}`,
    '',
    '## Context',
    '',
    adr.context ?? '_Not recorded._',
    '',
    '## Decision',
    '',
    adr.decision ?? '_Not recorded._',
    '',
    '## Consequences',
    '',
    adr.consequences ?? '_Not recorded._',
    '',
  ];

  if (tasks.length > 0) {
    lines.push('## Implementing Tasks', '');
    for (const t of tasks) {
      lines.push(`- [${statusBadge(t.status as any)}] \`${t.slug}\` — ${t.title}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ── Overview (meta Kanban) ────────────────────────────────────────────────────

export function reportOverview(db: DatabaseSync, baselineRate: number = 0): string {
  const projects = db.prepare('SELECT * FROM projects ORDER BY created_at DESC').all() as Project[];
  const date = new Date().toISOString().slice(0, 10);

  const lines: string[] = [
    '# crux — Project Overview',
    `<!-- GENERATED by crux on ${date} -->`,
    '',
    `| Project | Type | Status | Tasks Done | Hours | ROI | Last Active |`,
    `|---|---|---|---|---|---|---|`,
  ];

  const warnings: string[] = [];
  let activeCount = 0;

  for (const p of projects) {
    const tasks       = tasksByProject(db, p.id);
    const done        = tasks.filter(t => t.status === 'done').length;
    const hours       = totalHours(db, p.id);
    const roi         = roiSummary(db, p.id);
    const roiScore    = hours > 0 ? roi.revenue / hours : null;

    const lastAudit   = db.prepare(
      'SELECT created_at FROM audit WHERE project_id = ? ORDER BY created_at DESC LIMIT 1'
    ).get(p.id) as { created_at: string } | null;
    const lastActive  = lastAudit ? lastAudit.created_at.slice(0, 10) : '—';

    const roiLabel = roiScore !== null ? `$${roiScore.toFixed(0)}/hr` : '—';
    const roiFlag  = baselineRate > 0 && roiScore !== null && roiScore < baselineRate && hours > 20 ? ' ⚠' : '';

    if (p.status === 'active') activeCount++;

    // Stall detection
    if (p.status === 'active' && lastAudit) {
      const daysSince = (Date.now() - new Date(lastAudit.created_at).getTime()) / 86400000;
      if (daysSince > 14) {
        warnings.push(`⚠  ${p.name}: ${Math.round(daysSince)} days inactive — consider pausing`);
      }
    }

    if (baselineRate > 0 && roiScore !== null && roiScore < baselineRate && hours > 20) {
      warnings.push(`⚠  ${p.name}: ROI ${roiLabel} vs $${baselineRate}/hr opportunity cost`);
    }

    lines.push(`| ${p.name} | ${p.type} | ${p.status} | ${done}/${tasks.length} | ${hours.toFixed(1)}h | ${roiLabel}${roiFlag} | ${lastActive} |`);
  }

  lines.push('');

  if (activeCount > 2) {
    warnings.push(`⚠  SPREAD: ${activeCount} simultaneously active projects — focus peak is typically 2`);
  }

  if (warnings.length > 0) {
    lines.push('## Signals', '');
    for (const w of warnings) lines.push(w);
    lines.push('');
  }

  return lines.join('\n');
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function statusBadge(status: Task['status']): string {
  const map: Record<string, string> = {
    'open':        '○ open',
    'in-progress': '◑ in-progress',
    'blocked':     '✗ blocked',
    'done':        '✓ done',
    'dropped':     '— dropped',
  };
  return map[status] ?? status;
}
